// /*
//   Auto-generated by Spline
// */

// import useSpline from '@splinetool/r3f-spline';
// import { OrthographicCamera } from '@react-three/drei';

// export default function Scene({ ...props }) {
// 	const { nodes, materials } = useSpline(
// 		'https://prod.spline.design/CJ4YWQN7V3rHnGsp/scene.splinecode'
// 	);
// 	return (
// 		<>
// 			<color
// 				attach='background'
// 				args={['#eaeaea']}
// 			/>
// 			<group
// 				{...props}
// 				dispose={null}>
// 				<scene name='Scene'>
// 					<mesh
// 						name='Sphere'
// 						geometry={nodes.Sphere.geometry}
// 						material={materials['Sphere Material']}
// 						castShadow
// 						receiveShadow
// 						position={[-36, -3, 0]}
// 						rotation={[Math.PI, -1.1, Math.PI]}
// 						scale={1}
// 					/>
// 					<OrthographicCamera
// 						name='1'
// 						makeDefault={true}
// 						far={10000}
// 						near={-50000}
// 					/>
// 					<hemisphereLight
// 						name='Default Ambient Light'
// 						intensity={1}
// 						color='#eaeaea'
// 					/>
// 				</scene>
// 			</group>
// 		</>
// 	);
// }
